spring:
  datasource:
    dbcp2:
      validation-query: select 1
      url: jdbc:mysql://133.186.244.96:3306/nhn_academy_35
      initial-size: '2'
      max-idle: '2'
      max-wait-millis: '2000'
      test-on-borrow: 'true'
      min-idle: '2'
      max-total: '2'
    password: axMR@qTbrJmguez4
    username: nhn_academy_35
    url: jdbc:mysql://133.186.244.96:3306/nhn_academy_35?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
    fetch-registry: 'true'
