spring:
  datasource:
    dbcp2:
      validation-query: select 1
      url: jdbc:mysql://133.186.241.167:3306/aiot01_txt
      initial-size: '2'
      max-idle: '2'
      max-wait-millis: '2000'
      test-on-borrow: 'true'
      min-idle: '2'
      max-total: '2'
    password: LiKvKi*5SUyHGipX
    username: aiot01_txt
    url: jdbc:mysql://133.186.241.167:3306/aiot01_txt?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
eureka:
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://admin:1234@125.6.39.120:8761/eureka
    fetch-registry: 'true'
