### device 전체 조회
GET http://localhost:8400/api/common/device

### device 단일 조회
GET http://localhost:8400/api/common/device/1

### device 추가
POST http://localhost:8400/api/common/device
Content-Type: application/json

{
  "deviceName": "test-device111",
  "cycle": "00:30:00"
}

### device 수정
PUT http://localhost:8400/api/common/device/4
Content-Type: application/json

{
  "deviceName": "change-test",
  "cycle": "00:15:00"
}

#### device 단일 조회 exception
#GET http://localhost:8400/api/common/device/0